version: '2.1'

services:

  # datastore for Kafka
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
    - '2181:2181'
    volumes:
    - 'zookeeper_data:/bitnami'
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
    - app
    container_name: "zookeeper"
    links:
    - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: zookeeper

  # Asynchronous messaging
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
    - '9092:9092'
    volumes:
    - 'kafka_data:/bitnami'
    environment:
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    - KAFKA_ADVERTISED_HOST_NAME=kafka
    - KAFKA_ADVERTISED_PORT=9092
    depends_on:
    - zookeeper
    networks:
    - app
    container_name: "kafka"
    links:
    - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: kafka

  # Tracing implementation with Spring Cloud Sleuth
  zipkin:
    image: 'openzipkin/zipkin'
    ports:
    - '9410:9410'
    - '9411:9411'
    networks:
    - app
    container_name: "zipkin"
    links:
    - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: zipkin

  # Service Discovery
  consul:
    image: 'bitnami/consul:latest'
    ports:
    - '8300:8300'
    - '8301:8301'
    - '8301:8301/udp'
    - '8500:8500'
    - '8600:8600'
    - '8600:8600/udp'
    environment:
    - CONSUL_BOOTSTRAP_EXPECT=1
    - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
    - CONSUL_DISABLE_KEYRING_FILE=true
    - CONSUL_RETRY_JOIN_ADDRESS=consul
    volumes:
    - 'consul-data:/bitnami'
    networks:
    - app
    container_name: "consul"
    depends_on:
    - fluentd
    links:
    - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: consul

  # Log Aggregation system
  loki:
    image: grafana/loki
    ports:
    - 3100:3100
    networks:
    - app
    container_name: "loki"
    depends_on:
    - fluentd

  # Dashboard, pulls logs from Loki
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    networks:
    - app
    container_name: "grafana"
    depends_on:
    - loki

  # Forwards application logs to Loki
  fluentd:
    image: grafana/fluent-plugin-loki
    ports:
    - 24224:24224
    environment:
      LOKI_URL: http://loki:3100
    container_name: "fluentd"
    networks:
    - app
    volumes:
    - ./config/fluentd/fluent.conf:/fluentd/etc/fluent.conf

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  consul-data:
    driver: local
networks:
  app:
    driver: bridge